/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  conceptsSidebar: [
    {
      type: 'doc',
      id: 'concepts/concepts_overview',
    },
    {
      type: 'category',
      label: '基本',
      items: [{type: 'autogenerated', dirName: 'concepts/fundamentals'}],
    },
    {
      type: 'category',
      label: '応用',
      items: [{type: 'autogenerated', dirName: 'concepts/advanced'}],
    },
    {
      type: 'category',
      label: 'ネットワーク',
      items: [{type: 'autogenerated', dirName: 'concepts/network'}],
    },
    {
      type: 'category',
      label: '仕様',
      items: [{type: 'doc', id: 'concepts/specifications'}],
    },
  ],
  guidesSidebar: [
    {
      type: 'category',
      label: 'イントロ',
      items: [{type: 'autogenerated', dirName: 'guides/introduction'}],
    },
    {
      type: 'category',
      label: 'Aleo Instructions',
      items: [{type: 'autogenerated', dirName: 'guides/aleo'}],
    },
    {
      type: 'doc',
      id: 'guides/program_upgradability',
    },
    {
      type: 'category',
      label: 'Aleoプログラムの雛形',
      items: [{type: 'autogenerated', dirName: 'guides/standards'}],
    },
    {
      type: 'category',
      label: 'SolidityからLeoへ',
      items: [{type: 'autogenerated', dirName: 'guides/solidity-to-leo'}],
    },
    {
      type: 'doc',
      id: 'guides/faqs',
    },
    {
      type: 'doc',
      id: 'guides/how_to_get_help',
    },
    {
      type: 'category',
      label: '貢献',
      items: [{type: 'autogenerated', dirName: 'guides/contribute'}],
    },
  ],
  sdkSidebar: [
    {
      type: 'doc',
      id: 'sdk/sdk_overview_hub',
      label: '概要',
    },
    {
      type: 'category',
      label: 'Guides',
      link: {type: 'doc', id: 'sdk/guides/overview'},
      items: [
        'sdk/guides/getting_started',
        'sdk/guides/create_account',
        'sdk/guides/deploy_programs',
        'sdk/guides/execute_programs',
        'sdk/guides/transfer_credits',
        'sdk/guides/managing_state',
        'sdk/guides/querying_network',
      ],
    },
    {
      type: 'category',
      label: 'API仕様',
      items: [
        {type: 'autogenerated', dirName: 'sdk/api-specification'},
        {
          type: 'category',
          label: 'WASM',
          items: [
            {type: 'doc', id: 'sdk/wasm/address', label: 'アドレス'},
            {type: 'doc', id: 'sdk/wasm/authorization', label: '承認'},
            {type: 'doc', id: 'sdk/wasm/boolean', label: 'ブール'},
            {type: 'doc', id: 'sdk/wasm/ciphertext', label: '暗号文'},
            {type: 'doc', id: 'sdk/wasm/execution', label: '実行'},
            {type: 'doc', id: 'sdk/wasm/execution_response', label: '実行のレスポンス'},
            {type: 'doc', id: 'sdk/wasm/field', label: 'フィールド'},
            {type: 'doc', id: 'sdk/wasm/group', label: 'グループ'},
            {type: 'doc', id: 'sdk/wasm/key_pair', label: '鍵のペア'},
            {type: 'doc', id: 'sdk/wasm/offline_query', label: 'オフラインクエリ'},
            {type: 'doc', id: 'sdk/wasm/plaintext', label: '平文'},
            {type: 'doc', id: 'sdk/wasm/private_key', label: '秘密鍵'},
            {type: 'doc', id: 'sdk/wasm/scalar', label: 'スカラー'},
            {type: 'doc', id: 'sdk/wasm/signature', label: '署名'},
            {type: 'doc', id: 'sdk/wasm/transaction', label: 'トランザクション'},
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'create-leo-app',
      items: [
        {type: 'doc', id: 'sdk/create-leo-app/app_installation', label: 'アプリケーション導入'},
        {type: 'doc', id: 'sdk/create-leo-app/tutorial'},
      ],
    },
  ],
  apisSidebar: [
    {type: 'autogenerated', dirName: 'apis'},
    {type: 'autogenerated', dirName: 'apis-old'},
  ],
};

module.exports = sidebars;
